bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent'
name = 'testAgent'
public_address = 'HcScjN8wBwrn3tuyg89aab3a69xsIgdzmX5P9537BqQZ5A7TEZu7qCY4Xzzjhma'
test_agent = true

[[dnas]]
file = '/Users/andrewdennis/Documents/Rust/fridgenote/dist/fridgenote.dna.json'
hash = 'QmRjWrk3RsznB1DvmLdbM8zpj3e5LmeNXhvaViVUpnF9N9'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 8888
type = 'http'

[logger]
state_dump = true
type = 'debug'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
